### ISSUE TITLE
Is it normal for MRI reconstruction tests to be particularly slow?

### ISSUE THREAD

**Issue by ZhengJianwei2** [HJ-harry/DiffusionMBIR#1]
![1678424012364](https://user-images.githubusercontent.com/25289979/224228339-f0f8b6e4-ab2e-4c0a-a1da-9777c5fc3b9d.jpg)
As the title suggests, I confirmed that the data inputs are on cuda.

**Comment by HJ-harry** [comment]
Both CT/MR recon should be slow. 8 hours seem normal.
