### ISSUE TITLE
Dropbox checkpoint deleted

### ISSUE THREAD

**Issue by JingTongsh** [HJ-harry/DiffusionMBIR#11]
Although in issue #3 you claimed that the pre-trained models were available, by now they have been deleted in dropbox. Would you please recover them?

**Comment by GentleDell** [comment]
Hi,

Since the author has not re-uploaded the pre-trained model, here is the one downloaded by my colleague last year for your reference  [checkpoint_185.pth](https://drive.google.com/file/d/1-TaLbg3-4gLwKH2-Qf5VBFCBLG3RjY9j/view?usp=sharing). 

Please let me know if this pre-trained mode works on your side.

Best,

**Comment by JingTongsh** [comment]
Thanks. Actually I found that a colleage of mine had download the file :)

**Comment by jmsweng** [comment]
Hi,
I tried using the pretrained model GentleDell uploaded and I don't seem to be able to reproduce the results in the paper (my output seems to just be static). Would it be possible for someone else to upload the pre-trained model somewhere?

Thanks

Edit: Never mind, I had something configured incorrectly, the model GentleDell uploaded works. Thanks!

**Comment by wenwen2001** [comment]
> Hi, I tried using the pretrained model GentleDell uploaded and I don't seem to be able to reproduce the results in the paper (my output seems to just be static). Would it be possible for someone else to upload the pre-trained model somewhere?
> 
> Thanks
> 
> Edit: Never mind, I had something configured incorrectly, the model GentleDell uploaded works. Thanks!

Hello, I downloaded the weights uploaded by GentleDell and conducted experiments. The number of iterations of ADMM was set to 40, but it did not reproduce the effect in the paper. The PSNR was only 11.170 and the SSIM was only 0.3931. I would like to ask if anyone has successfully reproduced it. The results in the original paper appeared, but I didn't understand what was wrong with my reproduction.
![图片](https://github.com/user-attachments/assets/1425460d-10ea-4595-a53e-3f5352ff1d3f)
![图片](https://github.com/user-attachments/assets/3cbb6788-6139-4548-8b0c-053d363a452a)

**Comment by wenwen2001** [comment]
> Hi, 你好，
> 
> Since the author has not re-uploaded the pre-trained model, here is the one downloaded by my colleague last year for your reference [checkpoint_185.pth](https://drive.google.com/file/d/1-TaLbg3-4gLwKH2-Qf5VBFCBLG3RjY9j/view?usp=sharing).由于作者没有重新上传预训练模型，这是去年我的同事下载的供您参考的 checkpoint_185.pth。
> 
> Please let me know if this pre-trained mode works on your side.请告诉我，这个预训练模式在你们这边是否正常工作。
> 
> Best, 最好的

Thank you for the weights you provided, it can run, although I may not have achieved the effect of the original paper because I have not adjusted other weights well.

**Comment by SMARK2022** [comment]
> Hi,
> 
> Since the author has not re-uploaded the pre-trained model, here is the one downloaded by my colleague last year for your reference [checkpoint_185.pth](https://drive.google.com/file/d/1-TaLbg3-4gLwKH2-Qf5VBFCBLG3RjY9j/view?usp=sharing).
> 
> Please let me know if this pre-trained mode works on your side.
> 
> Best,

Hi,

Thank you for kindly sharing **checkpoint_185.pth**—much appreciated! I’m currently working with the MRI variant and am specifically looking for the pre‑trained MRI model (**checkpoint_95.pth**). If your team still has a copy, could you please share it when convenient?

Thanks again for your help!!!!!
