### ISSUE TITLE
When testing BRATS_MRI, an error is reported and the image displayed is incorrect

### ISSUE THREAD

**Issue by ZhengJianwei2** [HJ-harry/DiffusionMBIR#2]
![image](https://user-images.githubusercontent.com/25289979/224532214-cbb7adc5-d9ad-4bf0-984e-19b61e4ac3d6.png)
![image](https://user-images.githubusercontent.com/25289979/224532234-b0c65641-dc50-429a-8d23-0bd235d0d8fd.png)
First of all, after running a long test, I get an error saying that there is no normalize in clear, which doesn't affect the saved image, but I really don't know why my saved output image looks like this.
![image](https://user-images.githubusercontent.com/25289979/224532299-ff8543f4-a9a6-4183-8472-d98bc2877dad.png)
is there a problem with normalization?

**Comment by HJ-harry** [comment]
I've fixed the `utils.py` file to include normalization if set to true. For the saved image, it seems like the reconstruction was not done properly. Could you check if the model checkpoint was loaded correctly?

**Comment by ZhengJianwei2** [comment]
![image](https://user-images.githubusercontent.com/25289979/224843282-04437aa4-5567-43a7-9e5e-c01343e8e94f.png)
According to the readme, I manually downloaded the dataset and the model and placed them in the appropriate locations. I re-downloaded the model and tested it again in my own environment and got the same results. According to your reply, just because the model is loaded and tests are performed does not mean it is loaded correctly, so how can I check that the model is loaded correctly?
![image](https://user-images.githubusercontent.com/25289979/224845176-07e18eb9-5b4d-4091-8aa5-00ec08bd5e0a.png)
![image](https://user-images.githubusercontent.com/25289979/224845549-ad437a9c-c545-4312-aa7e-b701ae9bb463.png)

**Comment by hyungjin-chung** [comment]
I fixed the loading script to account for the default location of the checkpoint. If NOT loaded correctly, it will log `WARNING:root:No checkpoint found at ...`. If loaded correctly, it will log `loaded checkpoint dir from ...`.

**Comment by hyungjin-chung** [comment]
Closing as there are no further comments
